---

- name: Synchronize Phoenix SQL
  synchronize: src="{{phoenix_src}}/sql" dest="{{phoenix_dir}}" delete=yes recursive=yes

- name: Delete Phoenix Gatling Resources
  file: path="{{phoenix_dir}}/gatling-classes" state=absent

- name: Synchronize Phoenix Gatling Resources
  synchronize: src="{{phoenix_src}}/gatling-classes" dest="{{phoenix_dir}}" delete=yes recursive=yes

- name: Create Directory for Gatling Results
  file: path="{{phoenix_dir}}/gatling-results" state=directory owner="{{user}}" mode="0777"

- name: Copy JAR
  copy: src={{phoenix_jar_src}} dest={{phoenix_jar}} mode="u+x,g+x,o+x"
  when: upload_phoenix_jar

- name: Restart Phoenix
  service: name=phoenix state=restarted enabled=yes
