---

- name: Find out Highlander path
  shell: "dirname $(dirname $(pwd))"
  register: highlander_path_out

- name: Set IC Default Fact
  set_fact:
    with_ic_value: false

- name: Set IC Fact
  set_fact:
    with_ic_value: true
  when: with_ic_input in prompt_yes

- name: Set Default Appliance Name
  set_fact:
    google_instance_name: "{{appliance_prefix}}-{{user}}-{{999999|random}}"
  when: google_instance_name == ""

- name: Overwrite Highlander .env.local
  template: src=env.local.j2 dest="{{highlander_path_out.stdout}}/.env.local"
