---

- name: Copy Orders Consumer Marathon JSON
  template: src=orders-sphex.json dest=/marathon/applications mode="u+rw,g+rw,o+r"

- name: Update Orders Consumer in Marathon
  shell: 'curl -X PUT -d@/marathon/applications/orders-sphex.json -H "Content-Type: application/json" http://{{marathon_server}}/v2/apps/orders-sphex'

- name: Restart Orders Consumer in Marathon
  shell: 'curl -X POST http://{{marathon_server}}/v2/apps/orders-sphex/restart'

- name: Get Orders Consumer Marathon tasks in `healthy` state
  shell: curl -sS -XGET http://{{marathon_server}}/v2/apps/orders-sphex | jq '.app.tasksHealthy > 0'
  register: healthy_tasks_available
  until: healthy_tasks_available.stdout == 'true'
  retries: "{{marathon_retries}}"
  delay: "{{marathon_delay}}"
