vpn_hostname: vpn.foxcommerce.com
vpn_networkname: vpn.foxcommerce.com
vpn_server_ip: 10.240.0.2
vpn_network: 10.8.0.0
vpn_server: 10.240.0.0 255.255.255.0
vpn_network_interface: ens4
vpn_port: 1194
openvpn_user: openvpn

OPENVPN_CA_EXPIRE: 3650
OPENVPN_KEY_EXPIRE: 3650
OPENVPN_KEY_SIZE: 2048

OPENVPN_KEY_COUNTRY: NL
OPENVPN_KEY_PROVINCE: ZH
OPENVPN_KEY_CITY: Gouda
OPENVPN_KEY_ORG: foxcommerce
OPENVPN_KEY_EMAIL: max@foxcommerce.com
OPENVPN_KEY_CN: foxcommerce
OPENVPN_KEY_NAME: foxcommerce.key
OPENVPN_KEY_OU: foxcommerce
