---

- name: Kill Auto Update Script If Present
  command: pkill --full /usr/bin/unattended-upgrade
  register: kill_result
  failed_when: kill_result.rc > 1
  changed_when: kill_result.rc == 0

- name: Remove Unattended Upgrades
  apt: name=unattended-upgrades state=absent

- name: Install Core Packages
  apt: name={{item}} state=latest force=yes
  with_items:
    - apt-transport-https
    - ca-certificates
    - debconf-utils
    - curl
    - htop
    - iotop
    - make
    - nmap
    - python-httplib2
    - python-pip
    - python-software-properties
    - software-properties-common
    - tmux
    - tree
    - unzip
    - vim
    - zip

- name: Create /etc/profile.d Directory
  file: path=/etc/profile.d state=directory

- name: Setup Unprivileged User
  command: /usr/sbin/usermod -a -G systemd-journal {{user}}

- name: Stop SSH Guard
  service: name=sshguard state=stopped enabled=no
  when: is_appliance or is_staging

- name: Install Bootstrap Scripts
  copy: src={{item}} dest=/usr/local/bin mode=775
  with_items:
    - bootstrap.sh
    - bootstrap_consul.sh

- name: Install AWS Bootstrap Script
  copy: src=bootstrap_consul_aws.sh dest=/usr/local/bin mode=775
  when: is_aws

- name: Copy logrotate to cron.hourly
  shell: mv /etc/cron.daily/logrotate /etc/cron.hourly || true

- name: Install Docker
  include: docker.yml

- name: Configure Swap
  include: swap.yml

- name: Configure VM limits
  include: limits.yml

- name: Cleanup
  include: cleanup.yml
