---

- name: Migrate Backend
  hosts: '{{hostname_b}}'
  become: true
  vars:
    user: "{{ ansible_user | default(lookup('env', 'USER')) }}"
  vars_prompt:
    - name: "hostname_b"
      prompt: "Enter a hostname for the backend"
      default: "backend"
      private: no
  roles:
    - { role: dev/db_ic}


- name: Migrate Amigo
  hosts: '{{hostname_a}}'
  become: true
  vars:
    user: "{{ ansible_user | default(lookup('env', 'USER')) }}"
  vars_prompt:
    - name: "hostname_a"
      prompt: "Enter a hostname for the amigo"
      default: "amigo"
      private: no

  roles:
    - { role: base/mesos_master}

- name: Migrate Frontend
  hosts: '{{hostname_f}}'
  become: true
  vars:
    user: "{{ ansible_user | default(lookup('env', 'USER')) }}"
  vars_prompt:
    - name: "hostname_f"
      prompt: "Enter a hostname for the frontend"
      default: "frontend"
      private: no

  roles:
    - { role: base/rsyslog}
