---

- name: Packer Appliance Base Image
  hosts: all
  become: true
  vars:
    user: ubuntu
    is_appliance: true
    db_host: localhost
    packing: true
  roles:
    - { role: base/common }
    - { role: base/languages }
    - { role: base/devkit }
    - { role: base/ssh_keys }
    - { role: base/secret_keys }
    - { role: base/ssl_certs }
    - { role: base/rsyslog }
    - { role: base/consul }
    - { role: base/consul_agent }
    - { role: base/zookeeper }
    - { role: base/confluent_platform }
    - { role: base/flyway }
    - { role: base/db }
    - { role: base/bottledwater }
    - { role: base/mesos }
    - { role: base/mesos_master }
    - { role: base/mesos_worker }
    - { role: base/mesos_consul }
    - { role: base/elasticsearch }
    - { role: base/elasticsearch-5 }
    - { role: base/kibana }
    - { role: base/nginx }
    - { role: base/consul_template }
    - { role: base/dashboard }
    - { role: base/pgweb }
    - { role: dev/db }
    - { role: dev/db_ic }
    - { role: dev/flyway }
    - { role: app/systemd }
