---

- name: Provision Returns Feature Branch Instance
  hosts: "{{hostname}}"
  become: true
  vars:
    user: "{{ ansible_user | default(lookup('env', 'USER')) }}"
    hostname: "{{ lookup('env', 'APPLIANCE_HOSTNAME') }}"
    dns_record: "{{ lookup('env', 'APPLIANCE_DNS_RECORD') }}"
    api_server: "{{dns_record}}.foxcommerce.com"
    self_host: "{{dns_record}}.foxcommerce.com"
    ashes_server_name: "{{dns_record}}.foxcommerce.com"
    storefront_server_name: "{{dns_record}}.foxcommerce.com"
    is_appliance: true
    is_redeploy: true
    with_base_seeds: true
    url_prefix_perfectgourmet: "/perfect-gourmet"
    url_prefix_topdrawer: "/top-drawer"
  roles:
    - { role: hotfix/db }
    - { role: hotfix/elasticsearch }
    - { role: hotfix/rsyslog }
    - { role: prod/migrate_phoenix_db }
    - { role: prod/migrate_middlewarehouse_db }
    - { role: dev/marathon }
    - { role: dev/marathon_consumers }
    - { role: dev/ic }
    - { role: ext/td/storefront, when: marathon_restart.storefront_td }
    - { role: ext/tpg/storefront, when: marathon_restart.storefront_tpg }
    - { role: dev/balancer }
    - { role: hotfix/mesos_consul }
    - { role: demo/balancer }

  handlers:
    - include: roles/base/consul_agent/handlers/main.yml
    - include: roles/base/mesos_consul/handlers/main.yml
