---

- name: Install Packages
  apt: name={{ item }} state=latest force=yes
  sudo: true
  with_items:
    - libgoogle-glog0v5
    - libbotan-1.10-1
    - libpqxx-4.0

- name: Copy Isaac
  copy: src={{isaac_src}} dest=/usr/local/bin/isaac mode="u+x,g+x,o+x"
  sudo: true

- name: Copy Service
  template: src=isaac.service dest="{{dest_services}}/isaac.service"
  sudo: true

- name: Reload Systemd for Isaac
  sudo: yes
  command: systemctl daemon-reload

- name: Restart Isaac
  service: name=isaac state=restarted enabled=yes
  sudo: true

- name: Copy Consul Service File
  template: src=isaac.json dest="/etc/consul.d/isaac.json"
  sudo: true
  notify: reload consul
