apache_mirror: http://mirror.cogentco.com/pub/apache

avro_vers: 1.7.7
avro_name: "avro-{{avro_vers}}"
avro_c_name: "avro-c-{{avro_vers}}"
avro_url: "{{apache_mirror}}/avro/{{avro_name}}/c/{{avro_c_name}}.tar.gz"
avro_dir: "{{home}}/{{avro_c_name}}"

bottledwater_repo: https://github.com/confluentinc/bottledwater-pg.git
bottledwater_dir: "{{home}}/bottledwater"
bottledwater_version: 73692fc34aefcb6fcefe78fdf7193da92ba2e14a

flyway_vers: 4.0.3
flyway_dir: "/usr/local/share/flyway-{{flyway_vers}}"
flyway_url: "https://repo1.maven.org/maven2/org/flywaydb/flyway-commandline/{{flyway_vers}}/flyway-commandline-{{flyway_vers}}-linux-x64.tar.gz"
flyway: "{{flyway_dir}}/flyway -locations=filesystem:sql/ -configFile=sql/flyway.conf"

update_materialized_views_sql: "/usr/local/share/update_materialized_views.sql"
update_materialized_views_cmd: "psql {{db_connection_string}} -f {{update_materialized_views_sql}}"
drop_phoenix_replication_slot_cmd: "psql {{db_connection_string}} -c \"select pg_drop_replication_slot('{{bottledwater_slot_phoenix}}');\""
drop_middlewarehouse_replication_slot_cmd: "psql {{middlewarehouse_db_connection_string}} -c \"select pg_drop_replication_slot('{{bottledwater_slot_middlewarehouse}}');\""
drop_marketplace_replication_slot_cmd: "psql {{marketplace_db_connection_string}} -c \"select pg_drop_replication_slot('{{bottledwater_slot_marketplace}}');\""
