---

- name: Provision Packer Vanilla Kafka
  hosts: all
  tags:
      - packer-vanilla-phoenix
  vars:
    user: ubuntu
    packing: true
    phoenix_env: staging
    db_host: db.service.consul
    db_user: phoenix
    db_name: phoenix_development
    phoenix_tracing: "true"
    zipkin_collector: zipkin.service.consul
    log_host: es-log.service.consul
    phoenix_service_requires: ""
    phoenix_service_after: ""

  roles:
    - { role: base/ssh_keys }
    - { role: base/rsyslog, sudo: yes }
    - { role: base/phoenix }

  handlers:
     - include: roles/base/consul_agent/handlers/main.yml
