---

- name: Provision Packer Vanilla Db
  hosts: all
  tags:
      - packer-vanilla-db
  vars:
    user: ubuntu
    packing: true
    schema_server: schema-registry.service.consul:8081
    kafka_server: kafka.service.consul:9092
    log_host: es-log.service.consul

  roles:
    - { role: base/rsyslog, sudo: yes }
    - { role: base/consul_agent }
    - { role: base/db }
