---

- name: Provision Backend
  hosts: all
  vars:
    user: vagrant
  roles:
    - { role: base/common}
    - { role: base/consul}
    - { role: base/scala}
    - { role: base/kafka}
    - { role: base/elasticsearch}
    - { role: base/db}
    - { role: base/rsyslog, sudo: yes }
    - { role: base/kibana, sudo: yes }
    - { role: base/phoenix}
    - { role: base/greenriver}
    - { role: dev/db}
    - { role: dev/seeder}
    - { role: dev/greenriver}

  handlers:
     - include: roles/base/consul_agent/handlers/main.yml
