---

- name: Provision All The Things
  hosts: all
  vars:
    ashes_server_name: admin.foxcommerce.local
    firebird_server_name: firebird.foxcommerce.local
    firebrand_server_name: foxcommerce.local
  roles:
    - {role: base/common}
    - {role: base/consul}
    - {role: base/ssh_keys}
    - {role: base/scala}
    - {role: base/kafka}
    - {role: base/elasticsearch}
    - {role: base/db}
    - {role: base/rsyslog, sudo: yes }
    - {role: base/kibana, sudo: yes }
    - {role: base/node}
    - {role: base/balancer, sudo: yes }
    - {role: dev/db}
    - {role: dev/phoenix}
    - {role: dev/seeder}
    - {role: dev/greenriver}
    - {role: dev/ashes}
    - {role: dev/firebird}
    - {role: dev/firebrand}
    - {role: dev/balancer, sudo: yes }

  handlers:
     - include: roles/base/consul_agent/handlers/main.yml
