---

- name: Download Kibana
  get_url: >
    url=https://download.elasticsearch.org/kibana/kibana/{{kibana_name}}.zip
    dest=/usr/local/src/{{kibana_name}}.zip

- name: Extract and install Kibana
  unarchive: >
    src=/usr/local/src/{{kibana_name}}.zip
    dest={{kibana_dir}}
    copy=no
    creates={{kibana_dir}}/{{kibana_name}}

- name: Copy Kibana service
  template: src=kibana.service.j2 dest={{dest_services}}/kibana.service

- name: Reload Systemd for Kibana
  sudo: yes
  command: systemctl daemon-reload

- name: Restart Kibana
  service: name=kibana state=restarted
