proxygen_install_dir: "{{home}}/proxygen"
proxygen_version: "069658dc76ae41396fe106c24953837c42711584"

folly_install_dir: "{{home}}/proxygen/proxygen/folly"
folly_version: "f6b5f78bd533b91f51c3afc6d310698a42edb65d"

wangle_install_dir: "{{home}}/proxygen/proxygen/wangle"
wangle_version: "2c55f2bdcc84216c26c6058e754b874c3029e39f"
