---

- name: Add OpenVpn User
  user: name=openvpn

- name: Install Openvpn
  action: apt pkg={{ item }} state=latest
  with_items:
    - openvpn
    - easy-rsa
    - ufw
    - bridge-utils
    - udev

- name: Setup IPv4 forwarding
  command: echo 1 > /proc/sys/net/ipv4/ip_forward

- name: Add Default Foward Policy to UFW
  lineinfile: dest=/etc/default/ufw regexp='^#DEFAULT_FORWARD_POLICY' line='DEFAULT_FORWARD_POLICY="ACCEPT"' state=present

- name: Enable IPv4 Forwarding
  lineinfile: dest=/etc/sysctl.conf regexp='^#net.ipv4.ip_forward' line='net.ipv4.ip_forward=1' state=present

- name: Reload Sysctl config
  command: sysctl -p

- name: Install before.rules
  template: src=before.rules dest=/etc/ufw/before.rules

- name: Setup UFW connections on port 22
  shell: ufw allow 22/tcp

- name: Setup UFW connections on port for openvpn
  shell: ufw allow {{vpn_port}}/tcp

- name: Enable UFW
  shell: echo -e "y" | ufw enable

- name: Setting server config
  command: cp -r /usr/share/easy-rsa /etc/openvpn

- name: Install Openvpn Config
  template: src=server.conf dest=/etc/openvpn/server.conf owner=openvpn group=root

- name: Install Vars
  template: src=vars dest=/etc/openvpn/easy-rsa/vars mode=0700

- name: Install create-ca Script
  template: src=easy-rsa-initial-setup.script dest=/etc/openvpn/easy-rsa-initial-setup mode=0700

- name: run easy-rsa-initial-setup script
  shell: /etc/openvpn/easy-rsa-initial-setup

- name: Install Symlink for Keys
  file: state=link src=/etc/openvpn/easy-rsa/keys dest=/etc/openvpn/keys

- name: Make Keys Dr is Owned by Openvpn user
  shell: chown -R openvpn:root /etc/openvpn/easy-rsa/

- name: Make Sure Key Permissions Restricted
  shell: chmod -R 0660 /etc/openvpn/easy-rsa/keys/*.key

- name: Configure Iptables
  shell: sudo /sbin/iptables -t nat -A POSTROUTING -o {{vpn_network_interface}} -j MASQUERADE

- name: Copy OpenVPN Execution File
  template: src=run_openvpn.sh dest=/usr/local/bin/run_openvpn.sh mode="u+x,g+x,o+x"

- name: Copy OpenVPN Service
  template: src=openvpn.service dest="{{dest_services}}/openvpn.service"

- name: Reload Systemd for OpenVPN
  command: systemctl daemon-reload

- name: Restart Openvpn
  service: name=openvpn state=restarted enabled=yes
