---

- name: Provision Gatling Backend
  hosts: foxcomm-gatling-backend
  tags:
      - backend
  vars:
    user: '{{ansible_ssh_user}}'

  roles:
    - { role: dev/kafka }
    - { role: dev/elasticsearch }
    - { role: dev/db }

  handlers:
     - include: roles/base/consul_agent/handlers/main.yml

- name: Provision Gatling Ashes
  hosts: foxcomm-gatling-frontend
  tags:
      - ashes
  vars:
    user: '{{ansible_ssh_user}}'

  roles:
    - { role: base/ssh_keys }
    - { role: dev/phoenix }
    - { role: dev/messaging }
    - { role: dev/middlewarehouse }
    - { role: dev/isaac }
    - { role: dev/greenriver }
    - { role: dev/ashes }
    - { role: dev/firebrand }
    - { role: dev/balancer, sudo: yes }
    - { role: dev/consumers }

  handlers:
     - include: roles/base/consul_agent/handlers/main.yml

- name: Provision Gatling Gun
  hosts: foxcomm-gatling-gun
  tags:
      - gatling
  vars:
    user: '{{ansible_ssh_user}}'

  roles:
    - { role: test/gatling }
