---

- name: Packing Tinyprod Amigo
  hosts: all
  tags:
    - packer
  vars:
    user: ubuntu
    packing: true
    join_type: join
    mesos_quorum: 1
    consul_expect: 1
    zookeeper_server: "localhost:2181"

  roles:
    - { role: base/consul_server }
    - { role: base/zookeeper }
    - { role: base/docker_registry }
    - { role: base/mesos_master }
    - { role: base/mesos_consul }

  handlers:
     - include: roles/base/consul_agent/handlers/main.yml
